// src/pages/student/SkillAssessmentPage.tsx
import React, { useState } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import apiClient from '../../api/axios';
import { ArrowLeftIcon, ArrowRightIcon } from '@heroicons/react/24/outline';

// Define types for our data structures
type Stage = 'start' | 'loading_questions' | 'in_progress' | 'evaluating' | 'completed';
interface Result {
    total_score: number;
    max_score: number;
    verified: boolean;
    overall_review: string;
    detailed_results: {
        question: string;
        answer: string;
        rating: number;
        suggestion: string;
        marks: number;
    }[];
}

const SkillAssessmentPage = () => {
    const { skillName, skillId } = useParams<{ skillName: string; skillId: string }>();
    const navigate = useNavigate();
    
    const [stage, setStage] = useState<Stage>('start');
    const [questions, setQuestions] = useState<string[]>([]);
    const [answers, setAnswers] = useState<string[]>([]);
    const [currentQuestionIndex, setCurrentQuestionIndex] = useState(0);
    const [results, setResults] = useState<Result | null>(null);
    const [error, setError] = useState('');

    const handleStartTest = async () => {
        setStage('loading_questions');
        try {
            const response = await apiClient.post('/assessment/start/', { skill_name: skillName });
            setQuestions(response.data.questions);
            setAnswers(new Array(response.data.questions.length).fill(''));
            setStage('in_progress');
        } catch (err) {
            setError('Failed to generate questions. Please try again.');
            setStage('start');
        }
    };

    const handleAnswerChange = (e: React.ChangeEvent<HTMLTextAreaElement>) => {
        const newAnswers = [...answers];
        newAnswers[currentQuestionIndex] = e.target.value;
        setAnswers(newAnswers);
    };

    const handleSubmitAssessment = async () => {
        setStage('evaluating');
        const qa_pairs = questions.map((q, index) => ({ question: q, answer: answers[index] }));
        try {
            const response = await apiClient.post('/assessment/submit/', { skillId, qa_pairs });
            setResults(response.data);
            setStage('completed');
        } catch (err) {
            setError('Failed to evaluate your answers. Please try again.');
            setStage('in_progress'); // Go back to the questions
        }
    };

    // --- Render logic based on the current stage ---

    const renderStart = () => (
        <div className="text-center">
            <h2 className="text-3xl font-bold">Skill Assessment: {skillName}</h2>
            <p className="mt-4 text-gray-300 max-w-2xl mx-auto">
                You are about to start a text-based assessment to verify your skill. The test consists of 5 technical questions generated by our AI.
            </p>
            <div className="mt-8 flex justify-center gap-4">
                <button onClick={handleStartTest} className="bg-blue-600 px-8 py-3 rounded-lg font-semibold hover:bg-blue-700">
                    Start Text-based Test
                </button>
                <button className="bg-gray-600 px-8 py-3 rounded-lg font-semibold cursor-not-allowed opacity-50" disabled>
                    Start Voice Test (Coming Soon)
                </button>
            </div>
            {error && <p className="mt-4 text-red-400">{error}</p>}
        </div>
    );

    const renderInProgress = () => (
        <div>
            <h2 className="text-2xl font-bold mb-2">Question {currentQuestionIndex + 1} of {questions.length}</h2>
            <p className="text-lg text-gray-200 mb-6">{questions[currentQuestionIndex]}</p>
            <textarea
                value={answers[currentQuestionIndex]}
                onChange={handleAnswerChange}
                placeholder="Type your answer here..."
                className="w-full h-64 p-4 bg-gray-800 rounded-lg border border-gray-700 focus:ring-2 focus:ring-blue-500 focus:outline-none"
            />
            <div className="mt-6 flex justify-between items-center">
                <button
                    onClick={() => setCurrentQuestionIndex(i => i - 1)}
                    disabled={currentQuestionIndex === 0}
                    className="flex items-center px-4 py-2 bg-gray-600 rounded disabled:opacity-50"
                >
                    <ArrowLeftIcon className="h-5 w-5 mr-2" /> Previous
                </button>
                {currentQuestionIndex < questions.length - 1 ? (
                    <button
                        onClick={() => setCurrentQuestionIndex(i => i + 1)}
                        className="flex items-center px-4 py-2 bg-blue-600 rounded"
                    >
                        Next <ArrowRightIcon className="h-5 w-5 ml-2" />
                    </button>
                ) : (
                    <button onClick={handleSubmitAssessment} className="px-6 py-2 bg-green-600 rounded font-bold">
                        Submit Assessment
                    </button>
                )}
            </div>
        </div>
    );

    const renderLoading = (text: string) => (
        <div className="text-center">
            <div className="animate-spin rounded-full h-16 w-16 border-t-4 border-blue-500 mx-auto"></div>
            <p className="mt-4 text-xl">{text}</p>
        </div>
    );

    const renderCompleted = () => (
        results && (
            <div>
                <h2 className="text-3xl font-bold text-center mb-6">Assessment Results</h2>
                {/* Summary Card */}
                <div className="bg-gray-800 p-6 rounded-lg mb-8">
                    <div className="flex justify-between items-center">
                        <div>
                            <p className="text-gray-400">Final Score</p>
                            <p className="text-4xl font-bold">{results.total_score} / {results.max_score}</p>
                        </div>
                        {results.verified ? (
                            <div className="px-4 py-2 bg-yellow-500 text-gray-900 rounded-full font-bold">Skill Verified! 🎉</div>
                        ) : (
                            <div className="px-4 py-2 bg-red-500 text-white rounded-full font-bold">Try Again</div>
                        )}
                    </div>
                    <p className="mt-4 text-gray-300">{results.overall_review}</p>
                </div>

                {/* Detailed Breakdown */}
                <h3 className="text-2xl font-bold mb-4">Detailed Breakdown</h3>
                <div className="space-y-4">
                    {results.detailed_results.map((res, index) => (
                        <div key={index} className={`border-l-4 p-4 rounded-r-lg ${res.rating <= 4 ? 'border-red-500 bg-red-900/20' : 'border-green-500 bg-green-900/20'}`}>
                            <p className="font-bold text-gray-200">Q: {res.question}</p>
                            <p className="mt-2 p-3 bg-gray-900/50 rounded text-gray-300 whitespace-pre-wrap">A: {res.answer}</p>
                            <div className="mt-3 flex justify-between items-center text-sm">
                                <p className="font-semibold">AI Suggestion: <span className="font-normal text-gray-300">{res.suggestion}</span></p>
                                <p className="font-bold">Rating: {res.rating}/10</p>
                            </div>
                        </div>
                    ))}
                </div>
                <div className="text-center mt-8">
                    <button onClick={() => navigate('/profile')} className="bg-blue-600 px-6 py-2 rounded-lg">Back to Profile</button>
                </div>
            </div>
        )
    );

    const stageContent = {
        'start': renderStart(),
        'loading_questions': renderLoading('AI is generating your questions...'),
        'in_progress': renderInProgress(),
        'evaluating': renderLoading('AI is evaluating your answers...'),
        'completed': renderCompleted()
    };
    
    return (
        <div className="p-6 max-w-4xl mx-auto text-white flex items-center justify-center min-h-full">
            {stageContent[stage]}
        </div>
    );
};

export default SkillAssessmentPage;